import type { EngineeringHighlight, Feature, ProjectMetric, RouteConnection, RouteNode } from "./types";

const lc = (en: string, zh: string) => ({ en, zh });
const action = (en: string, zh: string) => lc(en, zh);

export const journeys = {
  prepare: lc("Prepare", "准备"), event: lc("Configure an event", "配置活动"), sell: lc("Sell", "售卖"),
  review: lc("Review", "复盘"), operate: lc("Operate", "运营"),
};

export const routes: RouteNode[] = [
  { id:"dashboard", journey:"prepare", path:"/", title:lc("Dashboard","仪表盘"), summary:lc("A focused overview of active events, stock warnings, and sales signals.","集中查看当前活动、库存预警和销售趋势。"), actions:[action("Resume recent work","继续最近工作"),action("Review sales and stock","查看销售与库存")], engineering:lc("Aggregates local SQLite data through dedicated services and Zustand selectors.","通过服务层和 Zustand selector 聚合本地 SQLite 数据。"), screenshot:"dashboard.png", related:["products","events","orders"] },
  { id:"products", journey:"prepare", path:"/products", title:lc("Products","制品管理"), summary:lc("Search, filter, group, import, and maintain a large merchandise catalog.","搜索、筛选、分组、导入并维护大型制品库。"), actions:[action("Create and batch import products","创建与批量导入制品"),action("Filter by tags and stock","按标签与库存筛选")], engineering:lc("Server-style SQLite pagination keeps large catalogs responsive without loading everything into memory.","SQLite 分页避免一次性加载全部数据，保持大型制品库流畅。"), screenshot:"products.png", related:["product-detail","product-groups","tags"] },
  { id:"product-detail", journey:"prepare", path:"/products/:id", title:lc("Product detail","制品详情"), summary:lc("Inspect identity, imagery, pricing, stock, variants, and event usage.","查看图片、价格、库存、多规格和活动使用情况。"), actions:[action("Edit or duplicate a product","编辑或复制制品"),action("Adjust and trace inventory","调整并追踪库存")], engineering:lc("Reusable detail composition is shared by full-page and modal contexts.","详情组件可在独立页面和弹窗上下文中复用。"), screenshot:"product-detail.png", related:["products","stock-logs","product-groups"] },
  { id:"stock-logs", journey:"prepare", path:"/products/stock-logs/:id", title:lc("Stock logs","库存记录"), summary:lc("Trace every stock movement back to its order, adjustment, or event.","将每次库存变化追溯到订单、调整或活动。"), actions:[action("Audit inventory changes","审计库存变化"),action("Follow related records","查看关联记录")], engineering:lc("Append-style inventory records make stock side effects explainable and auditable.","追加式库存日志让库存副作用可解释、可审计。"), screenshot:"stock-logs.png", related:["product-detail","orders"] },
  { id:"product-groups", journey:"prepare", path:"/product-groups/:id", title:lc("Product groups","多规格制品"), summary:lc("Manage related SKUs as one product family without losing individual stock.","将相关 SKU 作为同一制品家族管理，同时保留独立库存。"), actions:[action("Define variant dimensions","定义规格维度"),action("Manage linked SKUs","管理关联 SKU")], engineering:lc("Each variant remains a real inventory entity while the group provides shared presentation.","每个规格仍是独立库存实体，制品组负责共享展示。"), screenshot:"products.png", related:["products","product-detail"] },
  { id:"bundles", journey:"prepare", path:"/bundles", title:lc("Bundles","套装"), summary:lc("Package products together with automatically calculated availability.","组合多个制品，并自动计算可售数量。"), actions:[action("Create priced bundles","创建定价套装"),action("Preview component stock","预览子制品库存")], engineering:lc("Bundle availability is derived from component ratios rather than duplicated stock.","套装可售量根据子制品配比动态推导，不重复存储库存。"), screenshot:"bundles.png", related:["bundle-detail","products","events"] },
  { id:"bundle-detail", journey:"prepare", path:"/bundles/:id", title:lc("Bundle detail","套装详情"), summary:lc("Compose a bundle and understand its live stock constraints.","编排套装内容并理解实时库存约束。"), actions:[action("Add and reorder products","添加并排序制品"),action("Quick-restock components","快速补充子制品库存")], engineering:lc("Stock previews expose every component-side effect before changes are committed.","库存预览在提交前明确展示每个子制品的变化。"), screenshot:"bundle-detail.png", related:["bundles","product-detail"] },
  { id:"tags", journey:"prepare", path:"/tags", title:lc("Tags","标签管理"), summary:lc("Create a reusable classification system for catalog and event discovery.","建立可复用分类体系，用于制品与活动检索。"), actions:[action("Organize custom categories","管理自定义分类"),action("Bind and reorder tags","绑定并排序标签")], engineering:lc("Database-backed filtering stays complete even when lists are paginated.","数据库级筛选在分页场景下仍能返回完整结果。"), screenshot:"tags.png", related:["products","events"] },
  { id:"events", journey:"event", path:"/events", title:lc("Events","活动"), summary:lc("Prepare independent selling configurations for each convention.","为每场展会准备独立售卖配置。"), actions:[action("Create and duplicate events","创建或复制活动"),action("Start a selling session","开始出摊")], engineering:lc("Events reference reusable catalog entities while preserving event-specific order and rules.","活动复用制品库，同时保留独立排序与规则。"), screenshot:"events.png", related:["event-detail","selling","event-orders"] },
  { id:"event-detail", journey:"event", path:"/events/:id", title:lc("Event detail","活动详情"), summary:lc("Arrange products, bundles, groups, promotions, gifts, and selling order.","编排制品、套装、制品组、促销、赠品与售卖顺序。"), actions:[action("Import and sort merchandise","导入并排序制品"),action("Configure promotions and gift stock","配置促销与赠品库存")], engineering:lc("Event relations and sort order are persisted explicitly for deterministic POS rendering.","显式持久化活动关系与顺序，确保 POS 稳定渲染。"), screenshot:"event-detail.png", related:["events","selling","event-orders"] },
  { id:"event-select", journey:"sell", path:"modal:event-selector", title:lc("Event selection","选择活动"), summary:lc("Choose the correct catalog and rules before entering full-screen selling mode.","进入全屏售卖前选择正确的制品与规则。"), actions:[action("Select an event","选择活动"),action("Confirm selling context","确认售卖上下文")], engineering:lc("A guarded transition prevents orders from being attached to the wrong event.","受控跳转避免订单归属到错误活动。"), screenshot:"events.png", related:["events","selling"] },
  { id:"selling", journey:"sell", path:"/selling", title:lc("POS selling","出摊售卖"), summary:lc("A fast, landscape-first selling matrix designed for booth operation.","面向摊位操作的横屏快速售卖矩阵。"), actions:[action("Build and validate a cart","选品并校验购物车"),action("Take multilingual payments","进行多语言收款")], engineering:lc("Native grid modules, isolated cart state, and pre-checkout inventory validation keep selling responsive and safe.","原生网格、独立购物车状态与结算前库存校验兼顾速度与安全。"), screenshot:"selling.png", related:["event-select","payment","picking"] },
  { id:"payment", journey:"sell", path:"modal:payment", title:lc("Payment & receipt","支付与小票"), summary:lc("Guide payment, commit the order, and present a clear fulfilment receipt.","引导支付、写入订单并显示清晰的拣货小票。"), actions:[action("Choose a payment method","选择支付方式"),action("Complete or recover checkout","完成或恢复结算")], engineering:lc("Order creation and inventory deductions are coordinated as one service-layer workflow.","订单创建与库存扣减由服务层统一协调。"), screenshot:"selling.png", related:["selling","picking","orders"] },
  { id:"picking", journey:"sell", path:"local:picking", title:lc("Picking queue","拣货队列"), summary:lc("Coordinate fulfilment between the iPad and nearby phones over the local network.","通过局域网协调 iPad 与附近手机进行拣货。"), actions:[action("Claim and check items","领取并核对制品"),action("Track fulfilment state","追踪拣货状态")], engineering:lc("A provider-based local API uses claims, heartbeats, and stable picking codes without cloud dependency.","本地 Provider API 使用领取、心跳与稳定拣货码，无需云端依赖。"), screenshot:"selling.png", related:["selling","payment","event-orders"] },
  { id:"orders", journey:"review", path:"/orders", title:lc("Global orders","全局订单"), summary:lc("Search and analyze order history across every event.","跨活动搜索并分析全部订单历史。"), actions:[action("Filter and export orders","筛选并导出订单"),action("Refund, recover, and analyze","退款、恢复与分析")], engineering:lc("Paginated queries and dedicated aggregate queries keep history accurate at scale.","分页查询与独立聚合查询保证大数据量下的准确性。"), screenshot:"orders.png", related:["event-orders","stock-logs","dashboard"] },
  { id:"event-orders", journey:"review", path:"/orders/:eventId", title:lc("Event orders","活动订单"), summary:lc("Review sales, payment mix, and fulfilment for one event.","复盘单场活动的销售、支付构成与拣货。"), actions:[action("Inspect event performance","查看活动表现"),action("Manage order lifecycle","管理订单生命周期")], engineering:lc("Payment/refund status and picking status are modeled independently to avoid ambiguous state.","支付退款状态与拣货状态独立建模，避免状态歧义。"), screenshot:"event-orders.png", related:["event-detail","orders","picking"] },
  { id:"settings", journey:"operate", path:"/settings", title:lc("Settings","设置"), summary:lc("Control profile, selling preferences, security, data, and advanced capabilities.","管理资料、售卖偏好、安全、数据与高级能力。"), actions:[action("Configure payments and language","配置支付与语言"),action("Manage backup and access","管理备份与访问")], engineering:lc("Durable settings live in SQLite with explicit migrations from legacy storage.","持久设置存储于 SQLite，并支持旧存储的显式迁移。"), screenshot:"settings.png", related:["tags","pc-editor","picking"] },
  { id:"pc-editor", journey:"operate", path:"local:pc-editor", title:lc("LAN PC editor","局域网 PC 编辑器"), summary:lc("Edit a large catalog from a desktop browser while the iPad remains the source of truth.","在电脑浏览器编辑大型制品库，同时保持 iPad 为数据源。"), actions:[action("Edit catalog at desktop scale","在桌面端编辑制品库"),action("Work over the local network","通过局域网连接")], engineering:lc("A generated Vite application is served by an abstracted local-network provider.","生成的 Vite 应用由抽象局域网 Provider 提供服务。"), screenshot:"products.png", related:["settings","products"] },
];

export const connections: RouteConnection[] = routes.flatMap((route) => route.related.map((to) => ({ from: route.id, to })));

export const features: Feature[] = [
  ["offline", "Offline-first SQLite", "离线优先 SQLite", "Core workflows work without venue internet.", "核心流程不依赖展馆网络。", "shipped"],
  ["inventory", "Explainable inventory", "可解释库存", "Orders, bundles, gifts, and adjustments leave traceable effects.", "订单、套装、赠品和调整都留下可追踪记录。", "shipped"],
  ["promotions", "Promotions & gift stock", "促销与赠品库存", "Event rules support conditions, rewards, and independent gift pools.", "活动规则支持条件、奖励与独立赠品库存池。", "shipped"],
  ["picking", "LAN picking collaboration", "局域网拣货协同", "Nearby phones can fulfil orders without a cloud account.", "附近手机无需云账号即可协同拣货。", "beta"],
  ["i18n", "Three interface languages", "三种界面语言", "English, Japanese, and Simplified Chinese are built in.", "内置英语、日语和简体中文。", "shipped"],
  ["data", "Backup, restore & import", "备份、恢复与导入", "Portable local data with compatibility-aware restore previews.", "可迁移本地数据，并提供兼容性恢复预览。", "shipped"],
  ["plans", "Plan-based capabilities", "分级能力", "Centralized entitlements keep paid features consistent.", "集中式权益判断保证付费能力一致。", "beta"],
  ["analytics", "Deeper sales reporting", "增强销售报表", "Expanded day, week, and month reporting is planned.", "计划扩展日、周、月维度报表。", "planned"],
].map(([id,en,zh,den,dzh,status]) => ({ id, title:lc(en,zh), description:lc(den,dzh), status })) as Feature[];

export const engineering: EngineeringHighlight[] = [
  { title:lc("Layered data flow","分层数据流"), description:lc("Screens call Zustand stores, stores call services, and services own SQLite operations.","页面调用 Store，Store 调用服务，服务负责 SQLite 操作。"), technologies:["Zustand","Drizzle ORM","SQLite"] },
  { title:lc("Inventory correctness","库存正确性"), description:lc("Centralized checkout logic coordinates orders, bundles, gifts, refunds, and inventory logs.","集中式结算逻辑协调订单、套装、赠品、退款与库存日志。"), technologies:["TypeScript","Jest","SQL"] },
  { title:lc("Native performance where it matters","关键路径原生性能"), description:lc("Platform-specific grid modules support dense selling and sorting experiences.","平台原生网格模块支撑高密度售卖与排序体验。"), technologies:["Swift","Kotlin","Expo Modules"] },
  { title:lc("Operational resilience","运营韧性"), description:lc("Backup compatibility, monitoring, and automated quality gates protect a local-first product.","备份兼容、监控与自动化质量门禁保护本地优先产品。"), technologies:["Sentry","Firebase","GitHub Actions"] },
];

export const metrics: ProjectMetric[] = [
  { value:"15+", label:lc("Product routes","产品路由") }, { value:"16+", label:lc("Local data tables","本地数据表") },
  { value:"3", label:lc("Interface languages","界面语言") }, { value:"2", label:lc("Native platforms","原生平台") },
];
